project:
  type: website
  output-dir: docs

website:
  title: "Afiya Afnin Anika| STA 9750"
  description:
    Course Projects for STA 9750 at Baruch College
  site-url: "https://afiyanika.github.io/STA9750-2026-FALL/"
  navbar:
    background: primary
    search: false

format:
  html:
    theme: cosmo
    css: styles.css
    toc: false

editor:
  mode: source